#!/usr/bin/env bash
# install and configure nginx

# install
sudo apt-get update
sudo apt-get -y install nginx
# Configure Nginx to redirect /redirect_me
sudo sed -i 's|server_name _;|server_name _;\n\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}|g' /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
