#!/usr/bin/env bash
# edit nginx server to add header
# install
sudo apt-get update
sudo apt-get -y install nginx
# make owner
sudo chown -R $USER:$USER /var/www/html
# create html with hello world
echo "Hello World!" > /var/www/html/index.html
# get perm
sudo chown -R $USER:$USER /etc/nginx
# copy old file
cp /etc/nginx/nginx.conf /etc/nginx/nginx_old.conf
# sed edit current
sudo sed -i 's/# server_tokens off;/add_header X-Served-By $hostname;/g' /etc/nginx/nginx.conf
# reload
sudo service nginx reload
