#!/usr/bin/env bash
# edit nginx server to add header
# install
sudo apt-get update
sudo apt-get -y install nginx
# make owner
# get perm
sudo chown -R "$USER":"$USER" /etc/nginx
sudo chown -R "$USER":"$USER" /var/www/html
# create html with hello world
echo "Hello World!" > /var/www/html/index.html
# copy old file
cp /etc/nginx/nginx.conf /nginx_old.conf
# sed edit current
sudo sed -i 's/# server_tokens off;/&\n\tadd_header X-Served-By $hostname;/' /etc/nginx/nginx.conf
# reload
sudo service nginx reload
