#!/usr/bin/env bash
#transfer files to my server

# check if all 4 parameters are passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# assign parameters to variables
file_path=$1
ip_address=$2
username=$3
ssh_key=$4

# transfer the file using scp command
scp -o "StrictHostKeyChecking=no" -i "$ssh_key" "$file_path" "$username"@"$ip_address":~
