#!/usr/bin/env bash
# haproxy load balancr
# install
if ! command -v haproxy &> /dev/null; then
  sudo apt-get update &> /dev/null
  sudo apt-get install haproxy -y &> /dev/null
fi
# toggle enabling
sudo sed -i 's/#ENABLED=0/ENABLED=1/g' /etc/default/haproxy
# add frontend and backend
sudo sed -i '$afrontend http_front\n\tbind *:80\n\tdefault_backend www-backend\n\nbackend www-backend\n\tbalance roundrobin\n\tserver web-01 54.90.41.154:80 check\n\tserver web-02 52.91.160.206:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart &> /dev/null
# test
# cat /etc/haproxy/haproxy.cfg
