#!/usr/bin/env bash
# haproxy load balancr
# install
sudo apt-get update
sudo apt-get install -y haproxy
# verify install
haproxy -v
# toggle enabling
sudo sed -i 's/#ENABLED=0/ENABLED=1/g' /etc/default/haproxy
# add frontend and backend
sudo sed -i '$a\nfrontend http_front\n\tbind *:80\n\tdefault_backend www-backend\n\nbackend www-backend\n\tbalance roundrobin\n\tserver web-01 138847-web-01:80 check\n\tserver web-02 138847-web-02:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
