#!/usr/bin/env bash
# This script is displaying all bash id
# shellcheck disable=SC2009
while read line
do
  if [[ -f "/proc/$line/comm" && -r "/proc/$line/comm" ]]
  then
    cat "/proc/$line/comm" | xargs printf "$line %s\n"
  fi
done < <(pgrep bash)
