#!/usr/bin/env bash
# This script is displaying all bash id
# shellcheck disable=SC2009
while read -r line
do
  if [[ -f "/proc/$line/comm" && -r "/proc/$line/comm" ]]
  then
    xargs printf "$line %s\n" < "/proc/$line/comm"
  fi
done < <(pgrep bash)
