#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=1
while [ $x -lt 101 ]
do
  if [ $((x % 5)) == 0 ] && [ $((x % 3)) == 0 ]
  then
    echo "FizzBuzz"
  elif [ $((x % 5)) == 0 ]
  then
    echo "Buzz"
  elif [ $((x % 3)) == 0 ]
  then
    echo "Fizz"
  else
    echo "$x"
  fi
  x=$(( $x + 1 ))
done
