#!/usr/bin/env bash
# This script is displaying content of /etc/passwd
file="/etc/passwd"
# Each input line divided into seven fields separated by a colon (:) character
# https://www.cyberciti.biz/faq/unix-howto-read-line-by-line-from-file/
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
  # display fields using f1, f2,..,f7
  printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$f1" "$f4" "$f6" "$f7" "$f3" "$f2" "$f5"
done <"$file"