#!/usr/bin/env bash
# This script checks status of a file named school

if [[ -f school || -d school ]]
then
  echo "school file exists"
  if [[ -s school || -d school ]]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi
  # specifically checking if regular file
  if [[ -f school  ]]    # ← see 'man bash' for valid conditional statements.
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi